// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6Bgf65615TTtNAef2uToypBrDnKz78f4',
    appId: '1:154736637237:web:950e6a6853eb56ab7f087c',
    messagingSenderId: '154736637237',
    projectId: 'mapcords-8c556',
    authDomain: 'mapcords-8c556.firebaseapp.com',
    storageBucket: 'mapcords-8c556.firebasestorage.app',
    measurementId: 'G-S2MB7BMG1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW8XcIiE4Wk3Mzw59eF5J2Xl9N9eUw_9U',
    appId: '1:154736637237:android:ef027a21ad8203287f087c',
    messagingSenderId: '154736637237',
    projectId: 'mapcords-8c556',
    storageBucket: 'mapcords-8c556.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYV9b91dqbtBT4LZVwFqK5sHZh1m7VMbg',
    appId: '1:154736637237:ios:173051d92f100a767f087c',
    messagingSenderId: '154736637237',
    projectId: 'mapcords-8c556',
    storageBucket: 'mapcords-8c556.firebasestorage.app',
    iosBundleId: 'com.example.guardian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6Bgf65615TTtNAef2uToypBrDnKz78f4',
    appId: '1:154736637237:web:5db4b205fb8841d47f087c',
    messagingSenderId: '154736637237',
    projectId: 'mapcords-8c556',
    authDomain: 'mapcords-8c556.firebaseapp.com',
    storageBucket: 'mapcords-8c556.firebasestorage.app',
    measurementId: 'G-44QS2SH9CT',
  );
}
